import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.bg}>
        <Image layout="fill" objectFit="contain" src={"/assets/call.png"} />
      </div>

      <div
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          paddingLeft: "74px",
          // flex: 1,
          // margin: "auto 0",
          // alignItems: "center",
          // background: "red",
          height: "90vh",

          width: "100%",
        }}
      >
        <div style={{ fontSize: 34 }}>
          <h1>Inbound Outbound</h1>
          <h1>Call Center</h1>
          <h1>Solution</h1>
        </div>

        <div style={{ padding: "30px 0 30px 0", fontSize: 24 }}>
          <p>Professional solutions to facilitate contact with your client.</p>
          <p>We have been in the industry for over 19 years.</p>
        </div>

        <div>
          <Image
            // style={{ width: 200, height: 200 }}
            src={"/assets/gplay.png"}
            width={288}
            height={86}
            // layout="fill"
            objectFit="contain"
          />
          <Image
            // style={{ width: 200, height: 200 }}
            src={"/assets/appstore.png"}
            width={288}
            height={86}
            // layout="fill"
            objectFit="contain"
          />
        </div>
      </div>
    </div>
  );
}
